### ISSUE TITLE
Support for Xamarin

### ISSUE THREAD

**Issue by migueldeicaza** [Azure/service-fabric-services-and-actors-dotnet#1]
Would it be possible to package this software in a form that can be consumed by Xamarin?

We have a customer asking for Xamarin support for Service Fabric, specifically these libraries:

`Microsoft.ServiceFabric` and  `Microsoft.ServiceFabric.Services.Wcf`

**Comment by mi-hol** [comment]
@migueldeicaza @vturecek I wonder if this topic is getting discussed in an internal conversation? If yes, will you please share the result here?

**Comment by amanbha** [comment]
@migueldeicaza 
What kind of support are you looking for, exactly? Can you explain the scenario in more detail?

**Comment by migueldeicaza** [comment]
The packages would be compiled either as pure .NET standard, or compiled specifically for Xamarin.iOS and Xamarin.Android and published as NuGet packages.

**Comment by amanbha** [comment]
it will be a pure net standard nuget package.
