### ISSUE TITLE
Actor placement

### ISSUE THREAD

**Issue by saisworld** [Azure/service-fabric-services-and-actors-dotnet#101]
Hi,

I have few questions on the Actors and actor runtime

1) What is the placement strategy for newly created actors (not actor service)? Does it use metrics like VM's  currently available cpu or memory or existing running processes to determine where to place the actor? or does it use some hashing algorithm on the actorId and places the actor randomly on a vm irrespective of the its available cpu, memory etc?

2) Which process is responsible for this actor placement strategy? is it actor runtime or Service fabric runtime? 

I have conducted multiple experiments and I see no pattern in my results for the above mentioned scenario. Sometimes, actors were created on the same  vm as it was requested from.   I had total 5 vm's SF instance running with 2 core cpu and 8 gb ram. One partition of stateless service runs on all the vm's and 10 partitions of actor service are spread across the vm's. Stateless service creates multiple actors on the fly and waits for all the actors to complete the work (Task.waitall simple flow). Sometimes, I see that lots of requests and actors are concentrating on one node whereas another time they are evenly spread across 3 nodes. 

Problem I'm facing is due to multiple actors running on same vm, looks like its causing CPU starvation. When actors finish their work and return to stateless service, it sometimes takes good few seconds (I have seen 20 secs wait too) before returning  to the caller (stateless service). 

Any insights is really appreciated. 

Thanks
Sai

**Comment by amanbha** [comment]
@saisworld 
For placement a hash is generated from the ActorId, this hash is used as the partition key to determine which partition of the actor service the call should go to its irrespective of other resources. This partition key is determined at the ActorProxy when making the call and it sends the call to the correct partition.
If you use a long as ActorId then no hashing is done and its used as partition key.

For more info please see https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-introduction#distribution-and-failover

**Comment by saisworld** [comment]
Thanks @amanbha

I have also noticed in my experiments that some of the actors instantiated instantly after invoking them whereas for some there was a delay. Similarly, after processing has been finished in actor there was a delay in  return to the caller. Is this due to unavailable threads in the vm( where caller is running) or is something going on  in the actor runtime?

**Comment by amanbha** [comment]
There are no know issues in Actor Runtime causing the delay. When you say there was delay how was load distributed across various partitions of the actor service.  You can look at the performance counters for the .net and actors runtime to take a deeper look into what was going on  Actors performance counters are explained here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-diagnostics#performance-counters

**Comment by saisworld** [comment]
I understand there are no known issues. I want referring to known issues rather I was trying to understand what is going on the actor runtime. Is it trying to sort out lots of actors running, allocation, deallocation etc. Is that causing the delay? 

Just to add to my example (mentioned in my first message), below is the picture of the processing times of the Caller, Actor 1 and Actor 2. Total time was 8 seconds. Of which Actor-1 took one second and Actor-2 took 3 seconds (on a different vm) and when both completed, it took 3 seconds to return to the caller method. 

![image](https://user-images.githubusercontent.com/5602414/38082405-7f3c3748-333e-11e8-9580-df2984eb4899.png)

So what is causing that 3 seconds wait time ? I see this delay varies as lots of jobs are executed. However, when I execute only 1 job, there is no wait time, caller is ending immediately after both actors complete processing.

**Comment by amanbha** [comment]
Sure @saisworld. The actual method call while executing might be taking less time, but if there are more requests send to the service they need to wait until thread is available to execute it.
Could you look at the service remoting perf counters also when you experience this behavior (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-serviceremoting-diagnostics#list-of-performance-counters), specially the # of outstanding requests. Also how many cpu cores does the machine has?

**Comment by amanbha** [comment]
@saisworld I am closing this issue, please feel free to open issue if you still need help
