### ISSUE TITLE
Question: Polymorphism with actor StateManager

### ISSUE THREAD

**Issue by keggster101020** [Azure/service-fabric-services-and-actors-dotnet#103]
I've read the documentation on [polymorphism for actors](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-polymorphism) and I had a question on the inheritance of StateManager and state in actors.

Assuming I have an abstract class that is an actor
```csharp
    [ActorService(Name = nameof(AnActor))]
    [StatePersistence(StatePersistence.Persisted)]
    public abstract class AnActor: Actor, IRemindable
    {
        protected AnActor(ActorService actorService, ActorId actorId) : base(actorService, actorId)
        {
        }
       
        protected async Task SetState<T>(string stateKey, T toSave){
               ...
               await StateManager.AddOrUpdateStateAsync(stateKey, toSave, (s, t) => toSave);
        }

    }
```
And I have other actors that inherit from AnActor.
```csharp
    [ActorService(Name = nameof(AnotherActor))]
    [StatePersistence(StatePersistence.Persisted)]
    public class AnotherActor: AnActor
    {
        public AnotherActor(ActorService actorService, ActorId actorId) : base(actorService, actorId)
        {
        }
       
        protected async Task DoWork<T>(){
               ...
               await SetState("something", "some data here");
        }

    }
```

I am aware that StatePersistence isn't inherited to base classes.

With that in mind 

1. Is the state stored on the base class or in the derived class?

2. Does the base class need to specify StatePersistence?

**Comment by amanbha** [comment]
@keggster101020 answers to questions are below:
1. State is stored in the actor service created for the derived actor type.
2. StatePersistence on base actor is needed if you are not creating a service for it.  If you are creating a service for it and you don't specify the attribute, by default it will use None.

**Comment by keggster101020** [comment]
@amanbha I'm a little confused on the second answer. If I understand correctly, if the base class is a registered actor it may need the tag if it has it's own state but if it is not a registered actor and just a true base class then it needs the tag?

**Comment by keggster101020** [comment]
got it, thanks for the quick replies 😄
