### ISSUE TITLE
Service Remoting migration path

### ISSUE THREAD

**Issue by vturecek** [Azure/service-fabric-services-and-actors-dotnet#15]
Tracking the migration path for upcoming new Service Remoting features.

The new features in Service Remoting won't be compatible with the current Service Remoting listener and ServiceProxy. Users will need to follow a 3-phase migration path to successfully upgrade their services to use the new features:

 1. Service upgrade that adds the new version of the Service Remoting listener side-by-side with the current version.
 2. Client upgrade that switches to the new version of Service Proxy that is compatible with the new version of the Service Remoting listener.
 3. Service upgrade that removes the current version of the Service Remoting listener.

This means that there will need to be at least two releases of the Service Remoting NuGet package that has the current and new versions side-by-side. 

To make this work we'll need to either:
 1. Separate them out by namespace. 
 2. Use new class names.
 3. Keep a single set of Service Remoting classes that supports both old and new functionality, but we'll need to invent some new way to flag which version a service is using.

**Comment by NickDarvey** [comment]
Are there any details you can share about the new Service Remoting functionality @vturecek?
Perhaps... generics?

**Comment by suchiagicha** [comment]
Adding more details on how are we planning to release this new Remoting Stack.
1     We will be changing namespaces for existing Remoting stack to   Microsoft.ServiceFabric.Services.Remoting.Legacy ( name is not yet finalized) in 2.7 sdk release .
2    The new remoting stack will reside in current namespace Microsoft.ServiceFabric.Services.Remoting and will be released in 2.8 sdk . In 2.8 release , there will be 2 Remoting stack with different namespace. Class Name will remain the same but with added functionality. 
3 if someone creates new actor project, new remoting stack will come by default.

We will soon by posting about new features in Remoting stack.

**Comment by vturecek** [comment]
@NickDarvey primarily we're adding support for custom serialization and transport protocols. For the latter, we're adding HTTP as a transport option out of the box. In that case, ServiceProxy and ActorProxy will use HTTP, which also means you can address your remoting methods and actor methods directly over HTTP as well. We're also making some performance improvements to the TCP Fabric Transport we have today.

We won't have support for generics this time around. @suchiagicha can probably give more background on that.

**Comment by mholo65** [comment]
:+1: for custom serialization and transport! Great news!

**Comment by mholo65** [comment]
@vturecek for custom transport, does one have to rely on port sharing in order to run multiple partitions on same node? Or will it be possible to use different port on different partition?

**Comment by aL3891** [comment]
Great features!

I've been thinking about ways to pool actor proxies (to cut down allocations), essentially changing the actor id the proxy "points" to, with the transport layer opening up, is that something that would be possible to do?

**Comment by VipulM-MSFT** [comment]
@mholo65 - that is something for the transport provide to determine. Today if you want port and process isolation in the recently released version we allow option to run single replica per process. This means that for replica of a different partition we will spin up a new process and hence different port.

**Comment by juho-hanhimaki** [comment]
Will the new remoting make it to the next release?

Are there noticeable performance improvements out of the box or is it mostly left up to the users to optimize the serialization and transport?

**Comment by amanbha** [comment]
Closing this issue as the new remoting stack is now available with 2.8 SF SDK and 6.0 SF runtime release https://blogs.msdn.microsoft.com/azureservicefabric/2017/09/25/service-fabric-6-0-release/

If you have any questions, please feel free to reopen this or create a new issue.
