### ISSUE TITLE
Solution Unit Tests

### ISSUE THREAD

**Issue by lythix** [Azure/service-fabric-services-and-actors-dotnet#2]
I understand that this part of Service Fabric has only just been made Open Source, so it's possible any testing code may not yet have been made available. 
It's common for unit test projects to be along side the code being tested (ie in the same Solution). 

I was not sure where to ask this question so my apologies if this is the incorrect place to ask. Where are the Unit Tests located? Unit Tests are not only great for Testing, but also for new comers to help understand what individual units do and how they are supposed to work. 

Thank you.

**Comment by amanbha** [comment]
Yes, you are correct, we are starting to Open Source are programming model, product source code is the first step. Tests which we have  currently are written using internal tools. Part of it is due to history. Service Fabric was developed as internal service, our development process uses tools that aren't public. To be publishable, such issues have to be resolved. Tools either need to be replaced or themselves published  We will incrementally modify tests and add them to this repo so that they can be run without any dependency on internal tools.

**Comment by lythix** [comment]
Sounds excellent, looking forward to seeing the tests. Am interested in contributing and am especially interested in what is used to test, test style, mocking frameworks etc. 
Will keep an eye on this repo, I have an interest in Service Fabric but with no tests present making code changes sounds scary. 
Thank you

**Comment by amanbha** [comment]
That's great! yes, of course you can add unit tests, please use NUnit for writing unit tests and do a PR into the develop branch for this repo. Thanks.

**Comment by lythix** [comment]
Excellent, will do. 
I also noticed they use Moq in another Microsoft codebase I looked at (roslyn project-system), so will go with that. I've not yet figured out if each team use their own preference to tools or if Microsoft have a list of tools to try to be consistent. Visibility of that outside Microsoft isn't good.

**Comment by amanbha** [comment]
Using Moq is fine, I also updated my previous post to use xUnit, we just created the develop branch. Thanks

**Comment by vturecek** [comment]
@amanbha thanks!

@lythix yes you have a very valid point about standardized testing frameworks across Microsoft projects. A number of MS open source projects (across Azure and asp.net) are using either XUnit or MSTest (the test framework that ships with Visual Studio). So as @amanbha mentioned, we're jumping on the XUnit train as well.

**Comment by lythix** [comment]
@amanbha Thanks for not letting me get away with anything. :)
I've learned a lot just with this one pull request. It was my first real attempt at a pull request (hopefully it didn't show too much). May there be many more better ones to come. 

Also, if you can make available somehow some of the existing test (even if its just the tests themselves without the supporting unreleasable stuff) it will give me an idea of some more tests to write. 

The issue I am currently having in Visual Studio is that the unit tests are detected but they do not actually run. I'm sure its related to them being x64 but can't work it out. 

Thanks so much!

**Comment by amanbha** [comment]
Thanks @lythix for adding these initial set of unit tests, its great! I will share some tests after converting them to xUnit.
For the issue of running tests for x64 in VS: Could you check Test settings are set to x64. Its under the menu Test->Test Settings->Default Processor Architecture

**Comment by lythix** [comment]
Happy to help. I have a side project where I'm using Service Fabric, so the timing on this being open sourced is perfect. Conferted to xUnit or not, up to you. Happy to convert them if it saves you time.


Yes, the test settings are set to x64. Have done a bit of research as to the error and even created a runner config file.


I just tried running them on this laptop (different machine to where I tried them first) and got a similar error except I have gotten more meaningful error on the Test output window. Will edit this from that laptop with the error.

________________________________

**Comment by amanbha** [comment]
@lythix   Thanks for your help. I am closing this issue as now we have projects and solutions in place to add more unit tests. I have also converted more unittests to xunit and added to .csproj. For the xunit issue,, could you please open the issue in the xunit repo at https://github.com/xunit/xunit
