### ISSUE TITLE
Abstract base classes, implementing more than one actor interface require an ActorServiceAttribute attribute with valid Name on the abstract type.

### ISSUE THREAD

**Issue by BrainSlugs83** [Azure/service-fabric-services-and-actors-dotnet#22]
I have an abstract base class that implements a handful of actor interfaces, so that my actual classes don't need to deal with the nitty gritty.

The actual actor classes that implement more than one actor type, and require an explicit service name make sense; no problem there.

But requiring the base class (which is *abstract*!) to specify a service name does not make sense. -- It is the base class that all of my actors inherit from.

I can provide a code sample if needed, but this seems like a pretty straightforward issue.  The actual error message (from build output) is as follows:

> System.ArgumentException: The actor type MyNamespace.Actors.Framework.ExtendedActorBase implements more than one actor interfaces. In order for the client to connect to the right actor, please add Microsoft.ServiceFabric.Actors.Runtime.ActorServiceAttribute attribute with valid Name on the actor type. Please use this Name as serviceName parameter when creating ActorProxy.

Again, the error makes complete sense on a regular actor class, but on an abstract class, it's complete nonsense.

**Comment by amanbha** [comment]
@BrainSlugs83 Thanks for reporting it, will fix it in next release.
