### ISSUE TITLE
Minor bug in ActorStateProviderHelper/ExecuteWithRetriesAsync? -- Could be a one line fix.

### ISSUE THREAD

**Issue by BrainSlugs83** [Azure/service-fabric-services-and-actors-dotnet#23]
I've made this same typo before, and it's easy to miss; so, calling it out, just in case.

I'm looking at [ActorStateProviderHelper.cs:83](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/18667d8fabdf5edccd4e9782726c1316eff55dd8/src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateProviderHelper.cs#L83):
`effectiveRetryDelay = new TimeSpan(this.owner.TransientErrorRetryDelay.Seconds * 2);`

If the intention is to double the interval, it needs to be changed from `Seconds` to `TotalSeconds`, because `Seconds` will never be more than 60 (whereas `TotalSeconds` will be the total number of seconds that represent the TimeSpan).

Therefore, I recommend changing the line to this (assuming the intention is to actually double the interval):
<del>`effectiveRetryDelay = new TimeSpan(this.owner.TransientErrorRetryDelay.TotalSeconds * 2);`</del>
_(See edit!)_

Essentially the highest delay interval possible with the current code is just under 2 minutes; (i.e. 59.9999~ seconds * 2). -- If that's intentional then you can ignore this, but if it was a typo, then you should consider fixing it. :)

**EDIT:** 
As @aelij comments below, this is passing the value into the constructor, not the `TimeSpan.FromSeconds` method, so the code is actually very wrong, because it's passing in Seconds, where Ticks were expected.

Also, I'm noticing that it's only ever going to be the transient error retry delay * 2, and never grow any bigger.  Maybe that's intended, but it seems like you're expecting the code to double the current timespan.  In which case I recommend the following, as it might be more appropriate, and more readable:

`effectiveRetryDelay = TimeSpan.FromTicks(effectiveRetryDelay.Ticks * 2);`

(Passing ticks * 2 in the constructor should also work, but I recommend using the static method, because it says right there, in code what type of unit it is taking, and it makes it slightly harder to misinterpret what the code is doing.)

At any rate, if you're not trying to double `effectiveRetryDelay`, then please add a comment in the code as to what you are attempting to do. -- So that we can follow along with the logic.

Thank you!

**Comment by BrainSlugs83** [comment]
Alternately, if you meant to do it on purpose, maybe add a comment explaining the rationale (so that no one else sees it and tries to "fix" it).

**Comment by harahma** [comment]
Yeah that a typo. Thanks for catching it :). We will fix it in next CU release.

**Comment by aelij** [comment]
@BrainSlugs83 This should be `new TimeSpan(this.owner.TransientErrorRetryDelay.Ticks * 2)`, not `TotalSeconds`. Ticks are what the TimeSpan ctor expects (and are more accurate, being integers).

**Comment by BrainSlugs83** [comment]
Oh wow! -- Good catch.  -- You are correct. -- I am so used to calling `TimeSpan.FromSeconds`, I didn't even notice it was calling the constructor! -- Seems like a major bug in that case.

What I am used to calling is more like this `someTimeSpan = TimeSpan.FromSeconds(someTimeSpan.TotalSeconds * 2d)`. -- Again, good catch!

**Comment by BrainSlugs83** [comment]
Also -- I just realized, it's setting itself to some initial timespan value * 2 -- it's not actually doubling itself -- it's doubling some constant value (er static read-only, but still). -- Perhaps it is actually attempting to double itself? -- Anyway, I've updated my original post to the following recommendation:

`effectiveRetryDelay = TimeSpan.FromSeconds(effectiveRetryDelay.TotalSeconds * 2);`

(The ticks in the constructor should also work, but I recommend using the static method, because it says right there, in code, what type of unit it is taking, and it makes it slightly harder to misinterpret what the code is doing.)

At any rate, if you're not trying to double `effectiveRetryDelay`, then please add a comment in the code as to what you are attempting to do. -- So that we can follow along with the logic.

Thank you!

**Comment by amanbha** [comment]
Fix will be available in our next release.
