### ISSUE TITLE
Actor Trigger

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric-services-and-actors-dotnet#24]
Please provide a feature that will allow actors to be instantiated by external events such as database notifications, message queue, network events; having a actor the continually runs seems waste full while hooking the actor activation logic to an event seems the correct way to handle external events ? IMHO

**Comment by VipulM-MSFT** [comment]
We are working on the redesign that will separate out the actor dispatching logic from the transport and code generation. This should help addressing these scenarios.

**Comment by grahamehorner** [comment]
BTW I'm doing some experimental work around remote observer or observable with RX where an actor could either be instanciated by way of a OnNext, OnError or OnComplete from a Observable event push and/or produce events that would be consumed by one or more listeners either client side or within service fabric as another actor.
