### ISSUE TITLE
BadImageFormatException loading ServiceFabric assemblies (all x64)

### ISSUE THREAD

**Issue by Jose-CF** [Azure/service-fabric-services-and-actors-dotnet#30]
Steps to reproduce:

* Create a console application in VS 2017. Target any 4.6.x .NET Framework
* Set the target platform to x64
* Install ServiceFabric Nuget packages in the project: 
`
     <PackageReference Include="Microsoft.ServiceFabric" Version="5.6.220" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" Version="2.6.220" />
    <PackageReference Include="Microsoft.ServiceFabric.FabricTransport.Internal" Version="2.6.220" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="2.6.220" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="2.6.220" />
`
Notice that the version of the packages/assemblies is not relevant. I tried with many versions and the same problem appears.

* In your console application use anything from the ServiceFabric assemblies, just to make sure the ServiceFabric assemblies need to be loaded by the runtime.

* Build using MSBuild and set target platform to x64. Feel free to use different versions of MSBuild, same problem will appear.

* Once build, read your assemblies from another application to confirm target platform of all assemblies is x64, i.e. `assembly.GetName().ProcessorArchitecture`

* Check your system env variables to confirm x64 tooling has precedence over x86 tooling.

* Put the application in the service fabric VM of your servicefabric cluster. You can either copy the application manually to the VM or install it through servicefabric API. No difference (same problem appears).

* Run your application.

* Get this error:

![image](https://user-images.githubusercontent.com/24405049/28147590-f9ac8e88-67ab-11e7-8b6e-7ea3dce8c921.png)

I tried a huge amount of tricks and workarounds but always happy to try more.

Dependency walker says this: 
![image](https://user-images.githubusercontent.com/24405049/28147648-4bcb5744-67ac-11e7-86bf-966423329377.png)

Assembly Binder Log Entry says this:
![image](https://user-images.githubusercontent.com/24405049/28147699-86816a0e-67ac-11e7-9405-9089a4e42f22.png)

Not much documentation about error `0x80131018` on the net.
Any help is welcome.

I tried the different permutations of SF versions as follows:
For the cluster:

5.5.216.x
5.5.219.x
5.5.232.x

5.6.204.x
5.6.205.x
5.6.210.x
5.6.220.x
5.6.231.x (lately)

For the version of the nuget packages installed in the project we tried so far:

5.6.204.x
5.6.210.x
5.6.220.x
5.5.216.x
5.4.164.x

I also deleted the complete cluster and deployed a new one. Same problem.

Our VM images are MicrosoftWindowsServer 2016-Datacenter

**Comment by amanbha** [comment]
@Jose-CF  If you build it in VS, does it work? IS the Paltform target set to x64 in VS on Build tab of project properties.
![image](https://user-images.githubusercontent.com/11221966/28331529-4e54f4f4-6ba6-11e7-8b3f-401b7c1ebc5b.png)

**Comment by Jose-CF** [comment]
@amanbha 
As I state in my first message, I am building with VS. 
As I state in my first message, the target platform is x64

**Comment by amanbha** [comment]
@Jose-CF Could you please share your VS project and solution? You can mail them to me at amanbha@microsoft.com

**Comment by Jose-CF** [comment]
@amanbha I sent you per email an example. It is actually not relevant... you can reproduce the toy example with the tiny steps described in the issue.
We are really puzzled and not clue why this does not work any more.
We were using the ServiceFabric cluster for few months... then suddenly did not work any more... we also created new fresh VM's in the SF cluster... no difference. Whatever we do... `BadImageFormatException`

If we use dependency walker to see the ServiceFabric dll it would look like the dll is corrupted. But cannot be because we also tried with previous versions that were working flawlessly. Really puzzled.

**Comment by amanbha** [comment]
@Jose-CF  I am not able to repro this by just creating a console app and running it (Platform Target is set to x64 )in VS,
What is your Service Fabric cluster version? For using 2.6.220 nuget packages, cluster version must be at least 5.6.220 ?

**Comment by Jose-CF** [comment]
For the record of the issue I will add the SF versions I tried to the first message of this issue

**Comment by amanbha** [comment]
Resolved it over email with @Jose-CF . The binaries were corrupted in the application package on the machine.

**Comment by Jose-CF** [comment]
I want to really thank's @amanbha for his help and support.
I want to give a brief description of the problem so that it could potentially help other users:

Upon uploading the application package to the ServiceFabric cluster, some of the assemblies were corrupted. It means the binaries were not identical than the ones we tried to upload. So locally the binaries were correct, but when uploading, something failed and they were truncated/modified. However, nor ServiceFabric or the API used to upload them would prompt any error or warning.

Because only some of the assemblies were corrupted, the issue was difficult to spot. The application could start but it will fail when loading some assemblies.

We do not really know which exact version of the ServiceFabric cluster or CLI was causing this erroneous behavior.

Now uploading the package with Azure CLI 2.0.10 and running in the cluster 5.6.231.9494 works fine.
