### ISSUE TITLE
OnPostActorMethodAsync not called if method raises an exception

### ISSUE THREAD

**Issue by jackbond** [Azure/service-fabric-services-and-actors-dotnet#31]
I'm not sure if this is the intended behavior or not, but OnPostActorMethodAsync is not called if the actor method raises an exception. Whether it is intended or not, please make a note of it in the documentation.

Edit...

What would be really nice is if the existing version were deprecated, and replaced with something like...

protected override Task OnPostActorMethodAsync(ActorMethodContext actorMethodContext, Exception exception)

My thinking is, if you're going to have Pre/Post methods, it would be nice to know if the method completed successfully (in which case the exception would be null.)

**Comment by amanbha** [comment]
Thanks @jackbond  for the feedback, we will look into it. Adding @vturecek and @harahma for discussing it further as it will be a breaking change.

**Comment by jackbond** [comment]
@amanbha Did you guys ever reach a conclusion on this?

**Comment by amanbha** [comment]
@jackbond, sorry for the delay here, we are just busy with our next release, will discuss and update it here.

**Comment by amanbha** [comment]
OnPostInvoke is not called when exception is raised in actor methods. Will add explicitly to the method documentation that this is not called when exception is raised in actor method.
