### ISSUE TITLE
5.7.207.9494 is available in portal...

### ISSUE THREAD

**Issue by jackbond** [Azure/service-fabric-services-and-actors-dotnet#40]
Can't find any info on it. Any clues or is it a secret? :)

**Comment by vturecek** [comment]
Top secret, Mr. Bond. Seriously though yeah we'll have release notes out for this version soon, apologies for the delay.

**Comment by grahamehorner** [comment]
@vturecek any new features Q ? or just a handful of fixes ? 😉 waiting with baited breath

**Comment by vturecek** [comment]
@grahamehorner Mostly bug fixes, but there are a couple small new things like port override in ServiceManifest.xml.

**Comment by amanbha** [comment]
Our next release be 6.0, ETA couple weeks.
