### ISSUE TITLE
Remoting client hangs when trying to connect to non-existent URI

### ISSUE THREAD

**Issue by robbie-hughes** [Azure/service-fabric-services-and-actors-dotnet#41]
We have a very simple scenario where we are testing what happens when we try to attach a client to a cluster uri that does not exist. The purpose is to determine how the client reacts when the cluster is completely off-line. What we have found is that when the client calls a method on the service, it hangs indefinitely. We were expecting an exception to be thrown due to a timeout or connection not established, but the call never returned.
In the code below, we would expect for the line that calls "proxy.Test().Result" to throw an exception since the URI we supplied does not exist.
```c#
static void Main(string[] args)
{
	try
	{
		var factory = CreateProxyFactoryFabricTransport();
		var proxy = factory.CreateServiceProxy<IMyService>(new Uri("fabric:/BadAddress/Stateless1"));

		var result = proxy.Test().Result; // Client just hangs here...
		Console.WriteLine(result);
	}
	catch (Exception ex)
	{
		Console.WriteLine(ex);
		throw;
	}
	Console.ReadKey();
}

private static IServiceProxyFactory CreateProxyFactoryFabricTransport()
{
	var settings = new FabricTransportRemotingSettings
	{
		OperationTimeout = TimeSpan.FromSeconds(7),
		ConnectTimeout = TimeSpan.FromSeconds(5),
		MaxMessageSize = long.MaxValue
	};
	var retrySettings = new OperationRetrySettings(TimeSpan.FromMilliseconds(3), TimeSpan.FromMilliseconds(3), 0);

	var clientfactory = new ServiceProxyFactory((x) =>
	{
		return new FabricTransportServiceRemotingClientFactory(settings);
	}, retrySettings
	);
	return clientfactory;
}

public interface IMyService : IService
{
	Task<int> Test();
}
```

**Comment by suchiagicha** [comment]
@robbie-hughes
This is expected.  Since we retry on these case indefinitely. Assumption is service will eventually come up. We treat this as a failover scenario. 

You can use a cancellation token to achieve this. In your remoting Api , add a parameter for Cancellation token. Cancellation token is honored by remoting. When cancellation token is triggered, you will get OperationCancelledException.
