### ISSUE TITLE
Unexpected cast from TCommunicationClient to FabricTransportServiceRemotingClient

### ISSUE THREAD

**Issue by tophallen** [Azure/service-fabric-services-and-actors-dotnet#43]
I'm trying to override and extend the `FabricTransportServiceRemotingClient` to support a few custom headers, and in the Microsoft.ServiceFabric.Services.Remoting assembly file version 5.7.198.9494 it tries to perform a cast to `FabricTransportServiceRemotingClient` when I believe it should just be `TCommunicationClient` since that is what the `FabricTransportServiceRemotingClientImpl` class needs on that method.

Here is the offending code in `FabricTransportServiceRemotingClientFactory`:
```
Task<OperationRetryControl> ICommunicationClientFactory<IServiceRemotingClient>.
    ReportOperationExceptionAsync(
        IServiceRemotingClient client, 
        ExceptionInformation exceptionInformation, 
        OperationRetrySettings retrySettings, 
        CancellationToken cancellationToken)
{
    return this.impl.ReportOperationExceptionAsync(
        (FabricTransportServiceRemotingClient)client, 
        exceptionInformation, 
        retrySettings, 
        cancellationToken);
}
```

Is this a bug or am I missing something?

**Comment by tophallen** [comment]
I also posted this over [here](https://github.com/Azure/service-fabric-issues/issues/454) before I realized this had been open sourced - I have a workaround but it isn't pretty. I can make a PR this weekend if it would speed the fix going into a release. Thanks

**Comment by suchiagicha** [comment]
FabricTransportServiceRemotingClientImpl  assumes that TCommunicationClient is of type FabricTransportServiceRemotingClient . It has method for creating Client which creates client of type FabricTransportServiceRemotingClient .Hence there should not be case where client is not of type FabricTransportServiceRemotingClient .

Here is sample on how to add custom headers.  Look at it and let me know if you still see the issue.
https://github.com/Azure-Samples/service-fabric-dotnet-getting-started/tree/classic/Services/ServiceRemotingCustomHeaders

**Comment by tophallen** [comment]
@suchiagicha - Yes, I have already implemented it that way - but I don't see the reason why it couldn't be of type `TCommunicationClient` - the requiring of the cast seems like it's breaking the generic design. I guess I'm not sure why the `FabricTransportServiceRemotingClientImpl` class implements a strong type when everything else is generic or an interface. I don't see anything in the code that would force it to be that type. But I could be missing something.

**Comment by tophallen** [comment]
Actually - after digging a little further down I see why now it has to be that way. since you can't constrain a generic constructor beyond `new()` you wouldn't be able to create a generic client without some sort of `Initialize(params)` method on the interface. I guess this is not an issue. Thanks.
