### ISSUE TITLE
Internal/Protected

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric-services-and-actors-dotnet#46]
Please consider making internal protected/public to allow actor services derived from ActorService access to the property/methods so they can implement additional functionality

internal IActorActivator ActorActivator
internal ActorMethodDispatcherMap MethodDispatcherMap
internal ActorMethodFriendlyNameBuilder MethodFriendlyNameBuilder
internal IActorManager ActorManager

**Comment by amanbha** [comment]
Could you please explain the scenarios you foresee with this, we can add them to the framework itself.

**Comment by amanbha** [comment]
@grahamehorner , I am closing it as i didn't get any response, please feel free to open again.
