### ISSUE TITLE
GetActorReference not using IActorProxy breaks mock framework in release 2.8.211

### ISSUE THREAD

**Issue by Scythen** [Azure/service-fabric-services-and-actors-dotnet#49]
Previously ActorReference.GetActorReference cast the actor to an IActorProxy which allowed injection and test frameworks to support get actor ID. 

The latest version is now expecting a concrete ActorReference class which does not allow 3rd party libraries to provide custom implementations.

This change has broken our test framework. The logic in GetActorReference should support actors that implement IActorProxy regardless of the concrete type.

**Comment by VikSab** [comment]
this breaking our unit test framework

**Comment by amanbha** [comment]
@Scythen , @VikSab to understand it better, could you explain what is actually restricting here. Is it the fact that you were passing a mock of IActorProxy as object to ActorReference.Get(). That seems like a dependence on internal implementation as the method just took an object. I can make the change to check for IActorProxy first and get ActorId from it and get serviceUrl and listener name only when its of type ActorProxy, would just getting ActorId be enough here.

**Comment by Scythen** [comment]
@amanbha Yes, I was dependent on that internal implementation. However, in my defense there was no other way to create our own actor proxy for our service fabric mock framework. 

In order to create unit tests that both enforces serialization restrictions and concurrency restrictions on actors under test we implemented an actor proxy that isolated each actor during test. With this framework we can test single actors or simple actor interactions. However, q requirement for this is that the extension GetActorId work for our proxy objects. Because this method only relied on the object being either a real actor or an IActorProxy we were able to implement the required methods.

Our test framework was relatively simple to create and provides an environment much closer to that of Service Fabric. Prior to implementing this we often had serialization errors when deployed (because mocks did not serialize anything) or broken tests due to concurrency issues that would not exist when running in a real cluster.

As part of the test framework we had to deal with two implementation details that were hiding some required functionality. The implementation of GetActorId was one and the serialization and initialization of ActorReference was the other.

**Comment by amanbha** [comment]
@Scythen fair enough, so you only look for ActorId, let me think about an appropriate fix here without introducing another public api change. To unblock can your test infra pass Actor object to it as the method currently uses it as well as a fall back.

**Comment by Scythen** [comment]
We have passed the Actor object to tests that do not have concurrency issues but for many of our tests the isolation is required to ensure test code does not invoke actor methods concurrently.

**Comment by Scythen** [comment]
It seems like this should be very simple to fix with a slight change to the logic in GetActorReference. If the object is not an ActorProxy or an Actor but is an IActorProxy it should fall back to using the interface.

**Comment by amanbha** [comment]
@Scythen The ServiceUri which is a required DataMember of ActorReference is not available on IActorProxy. So In this fallback case ServiceUri will be set to EmptyString. Do your tests rely on ServiceUri as well? I can make this change but I still feel that its dependent on internal implementation of the method, looking at method signature, its not known if method takes a IActorProxy(now ActorProxy) or ActorBase.  If this fallback is removed again in future, it will break you guys again. I am open to suggestions to fix it a way so that it doesn't breaks in future, feel free to share a PR with changes.

**Comment by amanbha** [comment]
@Scythen I have made this change, will be available with our nuget packages released with our 6.1 SF runtime release (SDK nuget package version for it is not finalized yet).
// try as IActorProxy for backward compatibility as user's mock framework may rely on it.
            var actorProxyInterface = actor as IActorProxy;
            if (actorProxyInterface != null)
            {
                return new ActorReference()
                {
                    ActorId = actorProxyInterface.ActorId,
                    ServiceUri = new Uri(string.Empty)
                };
            }

**Comment by VikSab** [comment]
IActorProxy also implements/has property ActorServicePartitionClient along with ActorServicePartitionClientV2

why cant it mirror the code in previous if block? 

the service uri is still available in the implemented properties

**Comment by amanbha** [comment]
@VikSab because RemotingClient is on ActorProxy which is used to determine V1 or V2

**Comment by amanbha** [comment]
@VikSab, you can ignore the code snippet in previous comment, i have refactored it kept the first cast to IActorProxy instead of ActorProxy.

**Comment by amanbha** [comment]
Closing it as I have made the fix in our internal repo, it will be available with our nuget packages released with our 6.1 SF runtime release

**Comment by Scythen** [comment]
Is there an ETA for SF 6.1 runtime?

**Comment by amanbha** [comment]
@Scythen ETA is arnd 4 weeks, end of Nov 17.

**Comment by VikSab** [comment]
@amanbha  - nuget was released yesterday
https://www.nuget.org/packages/Microsoft.ServiceFabric.Actors/2.8.232
the fix doesnt seem to be in this release

**Comment by amanbha** [comment]
@VikSab that was an update to 6.0 runtime release, as I mentioned earlier the fix would be in 6.1 release.

**Comment by VikSab** [comment]
@amanbha - whats the ETA for Service fabric 6.1 - since its past Dec 2017 Week 1

**Comment by amanbha** [comment]
@VikSab  The build is going through final validations, should be out by next week. if it goes well.

**Comment by VikSab** [comment]
@amanbha  - any updates of the date?

**Comment by amanbha** [comment]
@VikSab We have to take more fixes for the release, so its been delayed a bit more, it will go through the cycle of build and validations, will keep you posted.

**Comment by amanbha** [comment]
@VikSab New nuget packages are available now. Thanks for being patient while we worked on this new release.
