### ISSUE TITLE
Make SegmentedPoolMemoryStream public

### ISSUE THREAD

**Issue by nrandell** [Azure/service-fabric-services-and-actors-dotnet#50]
I'm currently building a bond version of the V2 remoting serialization and want to use the SegmentedPoolMemoryStream - however it's internal only! Can this be made public?

**Comment by suchiagicha** [comment]
@nrandell 
Could you explain your usecase more in detail?
What do you mean by bond version of v2 remoting?

**Comment by nrandell** [comment]
I'm creating a custom remoting serialisation using https://github.com/Microsoft/bond. It would be more efficient to use the SegmentedPoolMemoryStream when I serialise the parameters. 
It will go up on GitHub soon so you can see it. For now I'm using reflection to create the stream and access the buffers inside it.

**Comment by suchiagicha** [comment]
SegmentedPoolMemoryStream  uses BufferPoolManager in order to re-use the buffers. If you want the same behavior in your serialization logic , you can use BufferPoolManager(which is public)  to maintain buffer pool . Then implement your stream class which uses bufferPool (which is very straightforward) .  I am not sure why you need to go for reflection?

**Comment by nrandell** [comment]
You guys have already done the work to create a stream backed by the buffer pool manager. I just wanted to reuse that. As that is internal, I have a method to create a new instance and another method to get the buffers.

```
        static ServiceRemotingRequestBondMessageBodySerializer()
        {
            var assembly = typeof(IBufferPoolManager).Assembly;
            var type = assembly.GetType("Microsoft.ServiceFabric.Services.Remoting.V2.Messaging.SegmentedPoolMemoryStream");
            var constructor = type.GetConstructor(new[] { typeof(IBufferPoolManager) });
            var ce = Emit<Func<IBufferPoolManager, Stream>>.NewDynamicMethod();
            ce.LoadArgument(0);
            ce.NewObject(constructor);
            ce.Return();
            _createSegmentedPoolMemoryStream = ce.CreateDelegate();

            var getBuffersMethod = type.GetMethod("GetBuffers");
            var gbe = Emit<Func<Stream, IEnumerable<IPooledBuffer>>>.NewDynamicMethod();
            gbe.LoadArgument(0);
            gbe.CastClass(type);
            gbe.CallVirtual(getBuffersMethod);
            gbe.Return();
            _getBuffers = gbe.CreateDelegate();
        }

        private static readonly Func<IBufferPoolManager, Stream> _createSegmentedPoolMemoryStream;
        private static readonly Func<Stream, IEnumerable<IPooledBuffer>> _getBuffers;
```
and I use it this way
```
        public OutgoingMessageBody Serialize(IServiceRemotingRequestMessageBody serviceRemotingRequestMessageBody)
        {
            var parameters = new object[_parameterCount];
            for (var i = 0; i < _parameterCount; i++)
            {
                parameters[i] = serviceRemotingRequestMessageBody.GetParameter(i, "", typeof(void));
            }
            var constructed = _payloadType.GetConstructors()[1].Invoke(parameters);
            using (var stream = _createSegmentedPoolMemoryStream(_bufferPoolManager))
            {
                var outputStream = new OutputStream(stream);
                var writer = new FastBinaryWriter<OutputStream>(outputStream);
                _serializer.Serialize(constructed, writer);
                outputStream.Flush();
                var buffers = _getBuffers(stream);
                return new OutgoingMessageBody(buffers);
            }
        }
```
As you can see the reflection is just used to build helper methods that access the internal class.

**Comment by suchiagicha** [comment]
I would recommend to not to rely on internal implementation. Being internal , means we can change it in future. So create copy of the  stream class and then use it. Our code is open-sourced .

We can think about making it  public in future release.

**Comment by jthelin** [comment]
Hi @nrandell - Looks like this library might help for your scenario? 

http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/

`Microsoft.IO.RecycableMemoryStream` is a drop-in replacement for MemoryStream, and does buffer pooling under the covers. It has been used internally by the Bing Team at Microsoft for long time now, so already battle-hardened.

Source code available on GitHub (MIT license) + binary package on NuGet.org -- see Ben Watson's blog post for more details.

**Comment by nrandell** [comment]
Thanks @jthelin  - I've seen this, but didn't use it. 
To be honest, I'm really surprised with what I'm seeing under the hood in the V2 of remoting. I was really excited to read about all the buffer pooling etc, to reduce memory pressure. However the implementation leaves my scratching my head a bit. As far as I can tell, there is a separate buffer pool manager used for each serialization interface, so there is still significant memory pool pressure added with many interfaces. Also the fact that the standard System.Buffers library (available in .netstandard 2.0) isn't used surprised me a lot.

What I was expecting to see was there to be a single shared System.Buffers.ArrayPool<byte> used as the central pool for all serialisation. This is how a lot of the Asp.Net core 'stuff' works. 

What I really do like is the way that the SegmentedPoolMemoryStream works, especially the way that large allocations are avoided by using a number of small buffers. I just wish it used a single shared ArrayPool.

Whilst I'm working on the bond serialisation, I was hoping to use a shared buffer pool manager, but it doesn't look like that will work. Ultimately I may implement a Bond.IO.OutputBuffer on top of a set of ArrayPool<byte> to handle serialisation and reduce memory.

Don't get me wrong - I'm really impressed with the recent work, but as my old boss always used to say, the reward for doing good work is being asked to do more!

**Comment by suchiagicha** [comment]
@nrandell 
We are using same bufferPoolManager at a listener level  . Multiple remoting interfaces will use same bufferPoolManager  if they are hosted under same listener.   BufferPoolManger is created for each ServiceRemotingDataContractSerializationProvider. Provider is created for each Listener Dispatcher.

All these interfaces are public and pluggable. You can implement these and use ArrayPool in the implementation.

**Comment by nrandell** [comment]
Thanks for the update @suchiagicha. I was just curious as to the decisions to create a new buffer pool mechanism rather than go with the standard ArrayPool.
