### ISSUE TITLE
Any reason why BufferPoolManager doesn't use the standard ArrayPool

### ISSUE THREAD

**Issue by nrandell** [Azure/service-fabric-services-and-actors-dotnet#51]
Really like the new V2 remoting support! One question though. Why don't you use the System.Buffers ArrayPool for handling this, rather than implementing a new BufferPoolManager.

**Comment by suchiagicha** [comment]
Currently we don't add dependency on external package like System.Buffers.
Also BufferPoolManager pools Object(PooledBuffer) . I am not sure if ArrayPool allows pooling of objects or it only for arrays. Otherwise both looks very similar.

**Comment by nrandell** [comment]
That's interesting given that System.Buffers is part of .netstandard 2.0 - I'm 100% certain it's used throughout kestrel in asp.net core (I'm sure @davidfowl can comment on this)

**Comment by amanbha** [comment]
@nrandell Looks like ArrayPool allows pooling of arrays, whereas BufferPoolManager pools PooledBuffer. There is no other specific reason for not using the ArrayPool. Please let me know if you have any other concerns with using BufferPoolManager else I will close this issue.

**Comment by nrandell** [comment]
I think my main reason for raising this was questioning why you use a different mechanism to pooling memory blocks to the mechanism that is standard in .Net. I was just surprised to see this in something that is some pretty core functionality as re-inventing techniques normally introduces bugs! As long as you guys are aware of the ArrayPool feature and have made the decision that it is not the correct thing to use, I'm happy for this to be closed.

**Comment by amanbha** [comment]
Thanks @nrandell , I understand your concern about reusing what is out there and appreciate pointing it out as we were not aware of it. We will look into leveraging this when we refactor next time. Thanks again!.
