### ISSUE TITLE
Optional parameters for remoting

### ISSUE THREAD

**Issue by Telavian** [Azure/service-fabric-services-and-actors-dotnet#52]
I added optional parameters to my IService implementation and came to found out that remoting doesn't support optional parameters. My question is why?

From what I understand the interface itself is a clear contract so there should be no ambiguity. Whether the caller sends the parameter or not changes nothing.

**Comment by amanbha** [comment]
Its in our backlog, its just that when we triaged backlog there are other high priority work items for the team.

**Comment by Telavian** [comment]
Sure I understand. Thanks.

**Comment by MattHartz** [comment]
Any update on this?
