### ISSUE TITLE
ReliableConcurrentQueue - warning log on TryDequeueAsync timeout

### ISSUE THREAD

**Issue by ElDiabloComputatore** [Azure/service-fabric-services-and-actors-dotnet#57]
If the queue is empty TryDequeueAsync operation  will wait for item to become available yet it still logs dequeue timeout as warning. Is the log entry/log level desired in this case?

**Comment by amanbha** [comment]
This repo is for Actors and Services layer. The issue seems to be for reliable collections, please open it in issues repo at https://github.com/azure/service-fabric-issues

**Comment by VipulM-MSFT** [comment]
@amanbha - can you move the issue to right place and assign to @sanchitgarg?

**Comment by amanbha** [comment]
@ElDiabloComputatore , synced with @sanchitgarg  and we will fix it in future release (tentatively it will be in 6.2 runtime release). Thanks!

**Comment by amanbha** [comment]
Closing it as this is fixed and will be available in 6.1 release (ETA first week of Dec)
