### ISSUE TITLE
FabUtil.exe with netcoreapp2.0 actors

### ISSUE THREAD

**Issue by pksorensen** [Azure/service-fabric-services-and-actors-dotnet#59]
I have some actors defined in a netcoreapp2.0 console application (using latest preview nugets of actors) but I cannot get fabutil to run on these projects.

First problem is that Microsoft.Service.Actors.dll is not actually in the bin folders. I copied them over myself until it stopped complaining.

```
System.BadImageFormatException: Could not load file or assembly 'file:///C:\dev\EarthML\EarthML.CarConnect\services\EarthML.CarConnect.Service\bin\Debug\netcoreapp2.0\win10-x64\EarthML.CarConnect.ServiceProvider.exe' or one of its dependencies. The module was expected to contain an assembly manifest.
3>File name: 'file:///C:\dev\EarthML\EarthML.CarConnect\services\EarthML.CarConnect.Service\bin\Debug\netcoreapp2.0\win10-x64\EarthML.CarConnect.ServiceProvider.exe'
3>   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
3>   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
3>   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
3>   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
3>   at FabActUtil.Tool.LoadInputAssembly(ToolContext context)
3>   at FabActUtil.Tool.ProcessInput(ToolContext context)
3>   at FabActUtil.Tool.Run(ToolArguments arguments)
3>   at FabActUtil.Program.Main(String[] args)
3>
3>WRN: Assembly binding logging is turned OFF.
3>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
3>Note: There is some performance penalty associated with assembly bind failure logging.
3>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
3>
3>
```
and trying on the dll instead of the exe

```
3>System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
3>   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
3>   at System.Reflection.Assembly.GetTypes()
3>   at FabActUtil.Tool.LoadActors(Assembly inputAssembly, IList`1 actorFilters, IList`1 actorTypes)
3>   at FabActUtil.Tool.LoadActors(ToolContext context)
3>   at FabActUtil.Tool.ProcessInput(ToolContext context)
3>   at FabActUtil.Tool.Run(ToolArguments arguments)
3>   at FabActUtil.Program.Main(String[] args)
```
So do we have to build the actors project on net462 to use fabutil?

**Comment by pksorensen** [comment]
I used the following workaround for now
My project.csproj file with the idea that on rebuild I will trigger a net462 build and run fabutil against that instead which updates the manifests.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework Condition="'$(MyProp)'==''">netcoreapp2.0</TargetFramework>
    <TargetFramework Condition="'$(MyProp)'=='hej'">net462</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <RootNamespace>EarthML.CarConnect.ServiceProvider</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cors">
      <Version>2.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.1" />   
    <PackageReference Include="Microsoft.Tpl.Dataflow">
      <Version>4.5.24</Version>
    </PackageReference>
    <PackageReference Include="S-Innovations.ServiceFabric.RegistrationMiddleware.AspNetCore2" Version="1.0.1-pre-2017111601" />
    <PackageReference Include="Serilog.Sinks.Literate" Version="3.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.4.0" />
    <PackageReference Include="WindowsAzure.Storage">
      <Version>8.6.0</Version>
    </PackageReference>
   </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EarthML.CarConnect.Abstractions\EarthML.AssetConnect.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EarthML.CarConnect.MunicIO\EarthML.AssetConnect.MunicIO.csproj" />
  </ItemGroup>

  <Target Name="MyPostBuildTarget" AfterTargets="AfterBuild" Condition="'$(MyProp)'=='hej'">
    <Exec Command="dotnet fabutil /spp:PackageRoot /t:manifest /sp:$(AssemblyName)  /local1nodeappparamfile:../../apps/EarthML.CarConnect.Application/ApplicationParameters/Local.1Node.xml           /local5nodeappparamfile:../../apps/EarthML.CarConnect.Application/ApplicationParameters/Local.5Node.xml       /app:../../apps/EarthML.CarConnect.Application/ApplicationPackageRoot /in:./$(OutputPath)$(AssemblyName).exe /arp:./$(OutputPath.TrimEnd('\'))" />
  </Target>
  <Target Name="MyPostBuildTarget2" AfterTargets="AfterRebuild">
    <Exec Command="dotnet restore /p:MyProp=hej" />
    <Exec Command="dotnet msbuild /p:MyProp=hej" />    
  </Target>
  <ItemGroup>
    <DotNetCliToolReference Include="S-Innovations.ServiceFabric.CoreCLR.Tools.FabUtil" Version="1.0.0-pre-2017111406" />
  </ItemGroup>
  
</Project>
```

**Comment by amanbha** [comment]
@pksorensen Templates for netcore Actor apps will be available in VS with Service Fabric 6.1 release (ETA 1st week of Dec) and with corresponding VS 2017 update. For now you can handcraft the manifests, or once you have generated them with your workaround, you can disable invoking of FabActUtil by adding property UpdateServiceFabricManifestEnabled as false to your actor csproj
@ravipal as fyi for VS templates.

**Comment by pksorensen** [comment]
Cool, i can use my own tooling until you guys are ready :)  `S-Innovations.ServiceFabric.CoreCLR.Tools.FabUtil` just wraps the fabutil and finds it in .nuget folder such it can be called with dotnet fabutil instead of .target files copy.

```
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;


namespace SInnovations.ServiceFabric.CoreCLR.Tools.FabUtil
{

    public class Program
    {
        [MTAThread]
        public static void Main(string[] args)
        {
               
 
            var basePath = string.Join("/", AppContext.BaseDirectory.Split(new[] { '/', '\\' })
                .TakeWhile(s => !s.Equals(".nuget", StringComparison.OrdinalIgnoreCase)));
            var actorPath = Path.Combine(basePath, @".nuget\packages\Microsoft.ServiceFabric.Actors");
            var versions = Directory.EnumerateDirectories(actorPath).Select(k => k.Substring(actorPath.Length + 1)).ToList();
          
           //TODO nuget versioning from current dependencies.
           var fileName = Path.Combine(basePath, $@".nuget\packages\Microsoft.ServiceFabric.Actors\{versions.Last()}\build\FabActUtil.exe");
            Console.WriteLine(fileName);
            if (!File.Exists(fileName))
            {
                throw new Exception("FabActUtil not found");
            }

            var actorlib = Path.Combine(basePath, $@".nuget\packages\Microsoft.ServiceFabric.Actors\{versions.Last()}\lib\net45\Microsoft.ServiceFabric.Actors.dll");


            // Fires up a new process to run inside this one
            var process = Process.Start(new ProcessStartInfo
            {
                UseShellExecute = false,

                RedirectStandardError = true,
                RedirectStandardInput = true,
                RedirectStandardOutput = true,

                FileName = fileName,
                Arguments = string.Join(" ",  args.Select(a=>$"\"{a}\""))
            });

            // Depending on your application you may either prioritize the IO or the exact opposite

            var outputThread = new Thread(outputReader) { Name = "ChildIO Output" };
            var errorThread = new Thread(errorReader) { Name = "ChildIO Error" };
            var inputThread = new Thread(inputReader) { Name = "ChildIO Input" };

            // Set as background threads (will automatically stop when application ends)
            outputThread.IsBackground = errorThread.IsBackground
                = inputThread.IsBackground = true;

            // Start the IO threads
            outputThread.Start(process);
            errorThread.Start(process);
            inputThread.Start(process);

            // Demonstrate that the host app can be written to by the application
            process.StandardInput.WriteLine("Message from host");

            // Signal to end the application
            ManualResetEvent stopApp = new ManualResetEvent(false);

            // Enables the exited event and set the stopApp signal on exited
            process.EnableRaisingEvents = true;
            process.Exited += (e, sender) => { stopApp.Set(); };

            // Wait for the child app to stop
            stopApp.WaitOne();

            // Write some nice output for now?
            Console.WriteLine();
            Console.Write("Process ended... shutting down host");
            Thread.Sleep(1000);

        }

        /// <summary>
        /// Continuously copies data from one stream to the other.
        /// </summary>
        /// <param name="instream">The input stream.</param>
        /// <param name="outstream">The output stream.</param>
        private static void passThrough(Stream instream, Stream outstream)
        {
            byte[] buffer = new byte[4096];
            while (true)
            {
                int len;
                while ((len = instream.Read(buffer, 0, buffer.Length)) > 0)
                {
                    outstream.Write(buffer, 0, len);
                    outstream.Flush();
                }
            }
        }

        private static void outputReader(object p)
        {
            var process = (Process)p;
            // Pass the standard output of the child to our standard output
            passThrough(process.StandardOutput.BaseStream, Console.OpenStandardOutput());
        }

        private static void errorReader(object p)
        {
            var process = (Process)p;
            // Pass the standard error of the child to our standard error
            passThrough(process.StandardError.BaseStream, Console.OpenStandardError());
        }

        private static void inputReader(object p)
        {
            var process = (Process)p;
            // Pass our standard input into the standard input of the child
            passThrough(Console.OpenStandardInput(), process.StandardInput.BaseStream);
        }
    }
}


```
if anyone is interested.

**Comment by amanbha** [comment]
Closing this one as templates for netcore Actor apps will be available in VS with Service Fabric 6.1 release (ETA 1st week of Dec)

**Comment by pksorensen** [comment]
@amanbha I still dont see any templates for actors on dotnet core. 

I saw in latest nuget release that there now is a dotnetcore2.0 folder in the build artifact of the nuget. But dotnet FabActUtil.dll indicate that it dont have any entrypoint. Whats the purpose of this? Can we use fabactUtil on dotnet core now?

**Comment by amanbha** [comment]
Templates will be in corresponding VS release. @ravipal Could you please share when VS 2017 Service Fabric tooling.

**Comment by ravipal** [comment]
@pksorensen The latest update (15.5.6) to VS 2017 will include the 2.0 service fabric tooling and it will have the actor core template.

**Comment by pksorensen** [comment]
@ravipal I am on 15.6 and its not there

![image](https://user-images.githubusercontent.com/2718591/35569647-f670d232-05cc-11e8-8b01-cb4cebc5d7a0.png)

![image](https://user-images.githubusercontent.com/2718591/35569699-1de0bc2e-05cd-11e8-964c-247f10628803.png)

![image](https://user-images.githubusercontent.com/2718591/35569729-348683d2-05cd-11e8-816d-581220ff9f82.png)

**Comment by ravipal** [comment]
You are on preview version of VS which didn't have the latest tooling. Yesterday we released an update to release version of VS (version: 15.5.6) which has the latest tooling that includes the Actor core template.

**Comment by pksorensen** [comment]
thanks @ravipal - any chance they also go into the preview version? I dont use anything else. But ofcause i can change to normal one if it wont happen

**Comment by ravipal** [comment]
We have a tentative plan to release a preview version of an another feature and that release will include the actor core template. The release timeline is not finalized, but should be next week or two. This will not be pushed to VS, instead we will publish a link to the tooling bits in azure fabric blog and you should be able to install on your preview VS.

**Comment by pksorensen** [comment]
I made a project in vs 15.5.6 and copied over things to my old projects and when building my ServiceManifest is updating correct. That is nice.

However, i am not sure. How do i get the _UpdateServiceFabricApplicationManifest target to run?  looking at the .targets file, it has the same condition as _UpdateServiceFabricServiceManifest - but application manifest do not get the new actor services added to the default service collection. Is this intended?

**Comment by pksorensen** [comment]
I was mistaken, none of the targets run. I also opened my service fabric project in visual studio 15.5.6 and it dont generate the service type either. It seems to work if I create a new project. I compared the csproj files and they are identical - but my old sf project dont update service types.

**Comment by ravipal** [comment]
When you create the actor project in 15.5.6 the following happens
1. The actor project will be created with the property \<FabActUtilWorkingDir>$(BaseIntermediateOutputPath)\FabActUtilTemp\</FabActUtilWorkingDir>
2. The project creation will install the Microsoft.ServiceFabric.Actors nuget package version 3.0.456, this nuget installation will generate the file obj\Actor1.csproj.nuget.g.targets which imports the target "microsoft.servicefabric.actors\3.0.456\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets"

When you copy the content make sure your old project has the above.

My suggestion would be to delete the import the latest Microsoft.ServiceFabric.Actors nuget package that will take care of including the right target.

**Comment by pksorensen** [comment]
Thanks mate, that worked.

I did not have the actors nuget packated installed since it was installed as a dependency of one of my common packages. Installing the actors nuget package explicit made everything work.

**Comment by pksorensen** [comment]
Another project where build wont generate.

When i try myself in powershell to run the FabActUtil i am getting the following error. 

Any ideas to why?

```
PS C:\dev\AscendXYZ\Ascend.Wammo.RadarIngestor\apps\Ascend.Wammo.RadarIgestor.ServiceProvider> dotnet "obj\\FabActUtilTemp\FabActUtil.dll"
Could not find required library hostpolicy.dll in 2 probing paths:
  C:\Users\pksor\.nuget\packages
  C:\Program Files\dotnet\sdk\NuGetFallbackFolder
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\dev\AscendXYZ\Ascend.Wammo.RadarIngestor\apps\Ascend.Wammo.RadarIgestor.ServiceProvider\obj\FabActUtilTemp\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\dev\AscendXYZ\Ascend.Wammo.RadarIngestor\apps\Ascend.Wammo.RadarIgestor.ServiceProvider\obj\FabActUtilTemp\FabActUtil.runtimeconfig.json file specifying the appropriate framework.
```

**Comment by pksorensen** [comment]
If i change my project to output win10-x64 runtime dependant.

I get:

PS C:\dev\AscendXYZ\Ascend.Wammo.RadarIngestor\apps\Ascend.Wammo.RadarIgestor.ServiceProvider> dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"" /in:"bin\Debug\netcoreapp2.2\win10-x64\\Ascend.Wammo.RadarIngestor.ServiceProvider.dll" /arp:"C:\dev\AscendXYZ\Ascend.Wammo.RadarIngestor\apps\Ascend.Wammo.RadarIgestor.ServiceProvider\bin\Debug\netcoreapp2.2\win10-x64\"

Unhandled Exception: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "FabActUtil.SR.resources" was correctly embedded or linked into assembly "FabActUtil" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at FabActUtil.CommandLineParser.CommandLineArgumentParser.Argument.ReportBadArgumentValue(String value)
   at FabActUtil.CommandLineParser.CommandLineArgumentParser.Argument.ParseValue(Type type, String stringData, Object& value)
   at FabActUtil.CommandLineParser.CommandLineArgumentParser.Argument.SetValue(String value, Object destination)
   at FabActUtil.CommandLineParser.CommandLineArgumentParser.ParseArgumentList(String[] args, Object destination)
   at FabActUtil.CommandLineParser.CommandLineArgumentParser.Parse(String[] args, Object destination)
   at FabActUtil.Program.Main(String[] args)
PS C:\dev\AscendXYZ\Ascend.Wammo.RadarIngestor\apps\Ascend.Wammo.RadarIgestor.ServiceProvider>
