### ISSUE TITLE
Service remoting long term plans and recommendations

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-services-and-actors-dotnet#60]
What are the future plans for service remoting?

V1 is to soon be deprecated, as far as I am aware, and has been replaced by the new V2 stack. So in that respect it seems like things arw moving forward however... It also feels to be to be a little neglected (re: my issues raised with ServiceProxy assuming just one stack used and not both) and it is a bit worrying to see the majority of SF team's samples, and talks, just use HTTP comms (kestrel)!

I did my own bit of testing and found that kestrel outperforms v2 remoting by about 20-25% for some basic RPC (e.g. `int GetAsync(int num);`) which seems a bit strange, I would expect asp.net with kestrel to have a load more overhead than this? (Although I have littlw understanding of the inner workings) 

Is it advised to just use kestrel and the built in reverse proxy (or dns for stateless) with some retry logic (e.g. polly) over service remoting?

**Comment by VipulM-MSFT** [comment]
@Mardoxx could you point at the ServiceProxy issue you referenced above.

Disclaimer: The statements below does not reflect any product plans.
The strongly typed interface based communication with location transparent proxy has it's own place in the micro-services world. In that world you want the network boundaries to fade, the objects can be moved around based on the load balancing but in future based on calling patterns and other data.  In this world the micro-services becomes even more micro, bunch of objects. The ServiceRemoting V2 is the first step in the right direction. It cleanly separates strongly typed implementation from the transport and serialization. This allows the code to be at the object level, but the communication may happen over HTTP through service mesh and data from that can be used to balance the resources in the cluster from various aspect.

The existing micro-services architecture for many applications today (especially containerized workload) communicate over HTTP using DNS or static IPs.  Their boundaries are explicit and well-defined.  These applications are easy to talk about, reason about and explain. 

The approach you take depends upon you scenario and there is no right or wrong answer.

**Comment by Mardoxx** [comment]
It was this one https://github.com/Azure/service-fabric-issues/issues/570
Some comments from one of your colleagues here too https://github.com/Azure/service-fabric-services-and-actors-dotnet/pull/55

Ahh I see. So if I understand correctly, this is where you'd use service fabric more as a framework than a platform for hosting microservices? In a case where you are less worried about setting up of inter-service comms and want to have these separate individually developed services which "target" service fabric.

**Comment by VipulM-MSFT** [comment]
Right, Service Fabric runtime provides the platform. The programming model (actors and services) makes use of this platform to provide higher level frameworks for building micro-services. These are only one example of the framework and we expect there may be more in the future. This repository being separate from the runtime was also first step towards making that boundary explicit. Today runtime and the framework ships together, but eventually it may not. I will respond on the other threads. Feel free to close this thread, if you have the right information.

**Comment by Mardoxx** [comment]
Brilliantly said thank you!
