### ISSUE TITLE
Remoting V2 Not utilizing ActorDataContractSurrogate

### ISSUE THREAD

**Issue by ikaros88** [Azure/service-fabric-services-and-actors-dotnet#62]
As far as i can see, transitioning to Remoting V2 breaks Actor Interface Methods that take other IActors as Parameters or return IActors.

In Remoting V1, this was made possible using the ActorDataContractSurrogate which forced Datacontractserializer to serialize ActorInterfaces as ActorReferences and Bind them during deserialization.

Would it be possible to mimic this behavior in Remoting V2? Otherwise i would have to transitions hundereds of interface methods to consume and return ActorReferences...this would also eliminate type safety in my interfaces as ActorReference is not generic and sealed.

**Comment by VipulM-MSFT** [comment]
@ikaros88 - thank for reporting the issue. 

While we are aware of the interface breaks with V2 remoting, that resulted from the fact that method parameters are not wrapped (and data contract serializer behaves differently for the top level objects and wrapped data members for the collections), this one was explicit design decision. 

V2 remoting stack offer customization of serialization and factories, we need to bind the interface to the proxy on the receiving side. If a factory other than the default factory is used for serialization we would not be able to do the bind. We are looking at an option where we can introduce the compatibility only for the default stack. However this means that if you later customize the stack with different transport or serializer, you may have to take care of binding the interface correctly. We are tracking the compatibility work under issue 590. https://github.com/Azure/service-fabric-issues/issues/590

**Comment by amanbha** [comment]
Closing this one as its tracked by https://github.com/Azure/service-fabric-issues/issues/590
