### ISSUE TITLE
Actor memory consumption with random id and manual delete

### ISSUE THREAD

**Issue by kbulte** [Azure/service-fabric-services-and-actors-dotnet#63]
We are using actors for image report processing in an IOT scenario and everything seems to be working fine until we checked memory consumption. We saw nodes with primaries using up to 4GB after a couple of days. To get an idea: A report contains 200 images and we start an actor for each image.  A report can be altered for a certain amount of time (let's say 20 minutes) and when altered the same actor is called(same id is used). After the time limit is reached (meaning the image report is final) we don't need the actor or it's state anymore and manualy delete the actor based on it's id:
```
IActorService myActorServiceProxy = ActorServiceProxy.Create(newUri("fabric:/Application16/ImageActorService"), id);
await myActorServiceProxy.DeleteActorAsync(id, default(CancellationToken))
```
When we delete the actors we see their OnDeactivateAsync method called in the applogs in application insights but the memory used by the actorservice process is not reducing.

So we thought it might be related to the processing logic itself (images manipulations you know) and we started testing with a stripped down version, the demo actor with the counter from the Service Fabric actor starter template on the local development cluster. The case: we start 200 actors instances of the demo actor from the starter template with a different id (ActorId.CreateRandom()) and then after 5 minutes we call the DeleteActorAsync method. 

When deployed to local cluster the initial memory footprint is 91.9MB based on sysinternals processexplorer.
After starting the actors by calling 200 of them with a random id 97.7MB is used.
5 minutes later we call the DeleteActorAsync() method which leaves us with 95.5MB.

I would expect after the deletion we should be close to 91.9MB again but this is not the case. If we repeat these steps a couple of times the memory usage of the actorservice process is rising.

And this for an actor that is only doing one simple thing:
` return this.StateManager.TryAddStateAsync("count", 0);`

If we do the same but reuse the ActorId meaning we go 200 times to the same actor every 30 seconds the memory consumption goes never beyond 93.7MB. This works as expected because the default garbage collection settings are put on 60 minutes and we ar keeping 1 Actor object alive by calling it every 30 seconds. So the actor object is never recreated. It seems the creation of a new actor instance is using more memory but is never releasing all of this memory. In this case with the demo actor the impact is small but for our actor used for image processing we have external dependencies to Azure blob storage which results in a much bigger impact on memory consumption.

Why is the actorservice process memory consumption rising? While we are deleting the actor object and it's state on disk via the DeleteActorAsync() method.
 I know about the memory leak regarding CancellationToken that was solved in SDK 2.7 [see](https://github.com/Azure/service-fabric-issues/issues/344). We are using **SDK 2.8.232**. 
Tests are done on the local cluster with **1 Node** and ApplicationManifest is not modified:
```
<Parameter Name="PartitionCount" Value="1" />
<Parameter Name="TargetReplicaSetSize" Value="1" />
<Parameter Name="MinReplicaSetSize" Value="1" />
```

**Comment by VipulM-MSFT** [comment]
@kbulte - Did you get chance to analyze the dump to see what objects are leaking and who is holding on to them? There is always going to be some increase due to use of various collections but the memory will stabilize after some time.

**Comment by kbulte** [comment]
@VipulM-MSFT - No didn't create a memory dump. Based on my tests we switched to a pool of actors (a set of ActorId's). We divide the image reports between these actors now. Memory is around 400MB now after 3 days compared to 3-5GB with random actor id's. We also thought the memory usage would stabilize but we never saw this actually happen. Taking in account the real load we would create in production this would never work. Still curious though.

**Comment by VipulM-MSFT** [comment]
Would it be possible to repro and take the dump to list the top objects? It would help speed up the analysis.

**Comment by amanbha** [comment]
@kbulte Do you have the dump with some initial analysis as suggested by Vipul above.

**Comment by amanbha** [comment]
@kbulte , I am closing this one because of lack of response, please feel free to reopen if help is needed regarding the issue. It would help speed things up, if you can do initial analysis on the dumps to see which objects are using the memory.
