### ISSUE TITLE
Service fabric actor with volatile state provider loses states during migration between replicas when register reminder with null state

### ISSUE THREAD

**Issue by MishaUliutin** [Azure/service-fabric-services-and-actors-dotnet#64]
Hello,
We have actor which uses volatile state provider and it loses its states and reminders registrations after moving primary to next node if reminder with null state was registered before. Everything works as expected if call RegisterReminderAsync method with empty array (new byte[0]) instead of null for state parameter or with persisted state provider.

**Comment by amanbha** [comment]
@MishaUliutin How many replicas does the actor service has? Volatile state provider keeps state in memory (its not persisted to disk) on replicas, so if all replicas go down, the state is lost. It works with persisted state provider as the state is persisted to disk.  @harahma for the behavior with reminder with null state, this seems incorrect if you had multiple replicas.

**Comment by harahma** [comment]
@MishaUliutin The state in the reminder should not impact the behavior. Which version of Service Fabric SDK are you using? Do you have a repro sample for this behavior?

**Comment by MishaUliutin** [comment]
>Which version of Service Fabric SDK are you using?

5.6.220/2.6.220

>How many replicas does the actor service has?

in my repro 3 replicas and 2 partitions

>Do you have a repro sample for this behavior?

yes, https://github.com/MishaUliutin/TestSfActors, you could repro it locally on local 5 Nodes cluster, so basically SF contains 2 service: 

1. Actor service (TestActor) with volatile state provider which has methods for get state and replica/partition info (GetValueAsync), create state (SetValueAsync), update state and register reminder (UpdateValueAndRegisterReminderAsync) 

2. Stateless service for hosts ASP .Net core web api with following api: 

- GET http://localhost:9000/api/value - for get call actor state and replica/partition info
- POST http://localhost:9000/api/value - for create actor state
- PUT http://localhost:9000/api/value - for update actor state and register reminder

For repro you should deploy my app locally on 5 Nodes and:

1. Call GET http://localhost:9000/api/value to ensure state/reminder does not exists. e.g. response:

> {
    "value": -1,
    "reminderExists": false,
    "nodeName": "_Node_3",
    "partitionId": "aabe49ae-457d-49a8-accf-7a06fe579ea3",
    "replicaId": "131575428691287007"
}

2. Call POST http://localhost:9000/api/value  for create actor state
3. Call GET http://localhost:9000/api/value to ensure state was created. e.g. response:
>{
    "value": 300,
    "reminderExists": false,
    "nodeName": "_Node_3",
    "partitionId": "aabe49ae-457d-49a8-accf-7a06fe579ea3",
    "replicaId": "131575428691287007"
}

4. Call  PUT http://localhost:9000/api/value - for update actor state and register reminder
5. Call GET http://localhost:9000/api/value to ensure state was updated/reminder was registered. e.g. response:
>{
    "value": 600,
    "reminderExists": true,
    "nodeName": "_Node_3",
    "partitionId": "aabe49ae-457d-49a8-accf-7a06fe579ea3",
    "replicaId": "131575428691287007"
}

6. Move primary replica to next node with powershell. e.g.:
> Connect-ServiceFabricCluster
Move-ServiceFabricPrimaryReplica -ServiceName fabric:/TestSfActors/TestActorService  -PartitionId aabe49ae-457d-49a8-accf-7a06fe579ea3

7. Call GET http://localhost:9000/api/value to ensure state/reminder was lost. e.g. response:
>{
    "value": -1,
    "reminderExists": false,
    "nodeName": "_Node_1",
    "partitionId": "aabe49ae-457d-49a8-accf-7a06fe579ea3",
    "replicaId": "131575445722414639"
}

Usually it reproduces for me 90% of time, if it does not just move primary replica with powershell one more time. My wild guess SF runtimes tries to promote next secondary replica to primary, it fails (probably fails to load reminder states and loses the replica state), so SF tries to promote next secondary replica to primary and again it fails and again...until all replicas lose state. And as I mentioned previously it works as expected if I use byte[0] instead of null for state in reminder.

**Comment by harahma** [comment]
Hello @MishaUliutin,

We have identified the bug and working on the fix. It should be available in our next release (v6.2/v6.1 CU).

Thanks again for providing the repro.

Regards,
Hasibur

**Comment by amanbha** [comment]
The fix would be available in 6.2 release and future 6.1 update releases.

**Comment by amanbha** [comment]
Fix for this issue is available in Microsoft.ServiceFarbic.Actors nuget package version >=3.0.467
