### ISSUE TITLE
How do you create .NET core (non ASP.net core) reliable services?

### ISSUE THREAD

**Issue by SamuelCox** [Azure/service-fabric-services-and-actors-dotnet#65]
Hi, I've spent a little time looking at the documentation for this, and none of it was immediately clear. When you create a service fabric project, you can add various services. Two of these options are ASP.net core stateless and stateful services. How do you create .NET core stateless and stateful services without ASP.net core?

The specific use case I'm thinking of is .NET core microservices that communicate over NServiceBus over some transport, so you just want service fabric for the reliable services features, and the state management feature, and you do not want any individual microservice exposed as an asp.net core webapi endpoint. Is this possible? When I created a stateless service, it automatically made it .net 4.6.1

**Comment by amanbha** [comment]
@SamuelCox  Please read throught his https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/12/visual-studio-2017-service-fabric-tools-2-0-preview/

**Comment by SamuelCox** [comment]
Ah that's perfect. Thanks for that. Wish it had come up when I googled.

**Comment by SamuelCox** [comment]
Any timeline on when this is coming out of preview?
