### ISSUE TITLE
Support control over ServiceBehavior on WcfCommunicationListener

### ISSUE THREAD

**Issue by kevinhillinger** [Azure/service-fabric-services-and-actors-dotnet#68]
Linking issue to pull request #34 so we can start tracking this feature.

Support through the interface, more control over ServiceBehavior.

**Comment by amanbha** [comment]
pull request #34 is merged and will be part of Service Fabric 6.2 release.

**Comment by kevinhillinger** [comment]
@amanbha Great news. Thanks for the update!
