### ISSUE TITLE
Unable to cast COM object of type 'System.__ComObject

### ISSUE THREAD

**Issue by ddobric** [Azure/service-fabric-services-and-actors-dotnet#69]
just installed new SF SDK 2.8.232.. and setup cluster 6.0.232.9494.
When starting Actor Client Application getting following error:

"Unable to cast COM object of type 'System.__ComObject' to interface type 'IFabricNodeContextResult2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{472BF2E1-D617-4B5C-A91D-FABED9FF3550}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))"

Using nugget Microsoft.ServiceFabric.Actors" Version="3.0.456"

Tried to downgrade nuget to 2.8 => compiling error :(

Thanks
Damir

**Comment by VipulM-MSFT** [comment]
It seems that you have FabricRuntime.dll in the path that is not compatible with the SDK you are using.

**Comment by ddobric** [comment]
It might be. What shell I do? How that happened? It was fresh machine.

**Comment by ddobric** [comment]
I think the currently available setup in PI is not correct.
I have installed the latest bits and get error described above.
Even more, the project template in VS is not in sync with SDK. For example following line cannot be compiled:
[assembly: FabricTransportActorRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)]

To make it working, I have to upgrade all nugget packages related to SF to newest.

**Comment by amanbha** [comment]
@ddboric Are you using VS 2015 or VS 2017? What was the default nuget package version it added on project creation?

**Comment by VipulM-MSFT** [comment]
@ddobric - The VS 2017 install link (http://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=MicrosoftAzure-ServiceFabric-CoreSDK) , installs the following:

Service Fabric SDK and Tools 3.0.456
Service Fabric runtime 6.1.456

You then need to update your VS 2017 installation to 15.5.6  release that includes the right templates.

**Comment by amanbha** [comment]
@ddobric Is this issue resolved for you now or you are still running into issues because of this.

**Comment by amanbha** [comment]
@ddobric I am closing this issue, please feel free to reopen if the issue still persists
