### ISSUE TITLE
Public events on CommunicationClientFactoryBase never get raised

### ISSUE THREAD

**Issue by jmblakl** [Azure/service-fabric-services-and-actors-dotnet#70]
**Steps to Reproduce**
Hook the public ClientConnected/ClientDisconnected events in service code
**Expected**
The public ClientConnected/ClientDisconnected events should be raised when handlers are provided to the events, and a client is either connected or disconnected.
**Actual Behavior**
The events are never raised.

Given a Communication Factory implementation of: 
```csharp
public sealed MyCommunicationClientFactory : CommunicationClientFactoryBase<MyCommunicationClient>
{
    //omitted for length
}

//in service class
var factory = new MyCommunicationClientFactory();
factory.ClientConnected += (s, e) => {
    // do someting
};
factory.ClientDisconnected += (s, e) => {
    // do someting
};
````
The outcome is that the events are never raised.

**Solution**
It looks like the protected constructor of CommunicationClientFactoryBase hard codes 'false' for the bool fireConnectEvents parameter to the internal constructor. Perhaps it is as simple as changing the internal cosntructor to a protected constructor?

```csharp
protected CommunicationClientFactoryBase(
            bool fireConnectEvents,
            IServicePartitionResolver servicePartitionResolver = null,
            IEnumerable<IExceptionHandler> exceptionHandlers = null,
            string traceId = null
        )
{
}
```

**Comment by jmblakl** [comment]
I would be more than happy to submit a PR for this, but wanted to see if there was a solid reason this shouldn't be exposed first.

**Comment by VipulM-MSFT** [comment]
@BharatNarasimman do you know why this is disabled?

**Comment by amanbha** [comment]
@jmblakl This seems like an oversight, you can submit a PR for it. Thanks for reporting it!

**Comment by amanbha** [comment]
Linking to pull request #71

**Comment by amanbha** [comment]
pull request #71 merged
