### ISSUE TITLE
IServiceRemotingRequestMessageBodySerializer should use IMessageBody and not OutgoingMessageBody/IncomingMessageBody

### ISSUE THREAD

**Issue by VipulM-MSFT** [Azure/service-fabric-services-and-actors-dotnet#82]
```csharp 
OutgoingMessageBody Serialize(IServiceRemotingRequestMessageBody serviceRemotingRequestMessageBody);
```

**should be** 
```csharp
IMessageBody Serializer(IServiceRemotingRequestMessageBody serviceRemotingRequestMessageBody);
```

and
```csharp
IServiceRemotingRequestMessageBody Deserialize(IncomingMessageBody messageBody);
```

**should be** 

```csharp
IServiceRemotingRequestMessageBody Deserialize(IMessageBody messageBody);
```

**Comment by Marusyk** [comment]
Hello @VipulM-MSFT, can I create PR for that or it should be discussed first?

**Comment by VipulM-MSFT** [comment]
@Marusyk - sure. We are currently fixing all of the coding style related issues to ensure consistency in the code. If you would like to wait until those are in that's fine as well as it will be easier to merge. We expect all style related fixes should be done in a week or so. We are fixing the documentation comments as part of this as well.

**Comment by Marusyk** [comment]
@VipulM-MSFT Thanks for answer
So, if you are currently fixing all then will be fixed this as well? Are you sure that I can make PR?

**Comment by Marusyk** [comment]
Can be closed. 
Thanks all
