### ISSUE TITLE
Will volatile actor use up any resources after its garbage collected.

### ISSUE THREAD

**Issue by woszszo** [Azure/service-fabric-services-and-actors-dotnet#84]
The documentation for the service fabric actors states that volatile actors are not persisted to disk. It states, as well, that after the actor is garbage collected it's completely removed from memory. Does it mean that the volatile actor is deleted during garbage collection?

I want to create a lot of volatile actors (with state) and I'm wondering if I should take care/worry about cleaning the resources they use.

**Comment by amanbha** [comment]
When you create actors with volatile state provider, state associated with actors is not persisted and is kept in memory. The state will be kept in memory until the actor is deleted, so it will keep using the memory. During GC of actors by actor runtime, only the actor instance is removed, it's state provider from stateprovider is not removed.

**Comment by woszszo** [comment]
This is very unexpected behavior. This should be stated clearly in the documentation. So I have further questions: 
1. What happens when the cluster runs of the memory?
2. Does empty state manager use any memory/can I release memory occupied by state manager by removing all the state from it?
3. Does your answer apply to non-persisted actor as well?

**Comment by amanbha** [comment]
@woszszo There seem to be some confusion in understanding the key concepts, please refer to our documentation at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-state-management#state-persistence-and-replication
I will try explain it here breifly: Actor state provider provides a state store for the actors, the state provider can be peristed, volatie or none. In case of vloatile the state is always stored in memory on the replicas. Actor state manager is a wrapper on top of state manager, when modifying the states for the actor you interact with state manager, the states which have been brouight into state manager is removed once the actor is garbage collected.

I hope that clarifies the confusion, I would urge you to read through the documentaion.

**Comment by woszszo** [comment]
@amanbha I've read the documentation SEVERAL times and I understand key concepts. Otherwise I haven't complained that "**This should be stated clearly in the documentation.**" in previous post. The documentation is ambiguous in many places unfortunately.

> During GC of actors by actor runtime, only the actor instance is removed, it's state provider from **stateprovider is not removed**.

>  the states which have been brouight into **state manager is removed** once the actor is garbage collected.

Could you elaborate? Because now I'm confused even more.

Is state manager removed by garbage collector or not? Is state itself removed by garbage collector or not? We are considering volatile actors. Please be precise.

**Comment by ap3rus** [comment]
There are two conflicting statements

> During GC of actors by actor runtime, only the actor instance is removed, it's state provider from stateprovider is not removed.

and 

> Actor state manager is a wrapper on top of state manager, when modifying the states for the actor you interact with state manager, the states which have been brouight into state manager is removed once the actor is garbage collected.

So what is the final answer to this, does state gets removed in case of volatile persistence when actor is garbage collected? The documentation https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-state-management#state-persistence-and-replication does not explicitly explains this behavior, it would be nice if there was a sentence clearing the ambiguity here.

**Comment by amanbha** [comment]
Sure, I will go through the doc and will make it clear to avoid confusion. 
I will try to explain further here (remember StateManager and StateProvider are 2 distinct concepts):
When Actor GC happens, actor's state which have been brought into StateManager is removed from memory, StateManager is a wrapper on top of state provider. Any state stored in state provider remains in state provider. Since VolatileStateProvider is an in memory state provider and keeps state in memory, so for VolatileStateProvider, state will always stay in memory until actor is deleted or its state is removed.

**Comment by woszszo** [comment]
I see, so state provider of volatile actor will keep using memory resources even if the actor itself is deactivated.

Does SF gives a guarantee that empty state provider doesn't use any memory (not even a byte)? I'm worried that it may use some memory for some metadata, even if the state itself was removed.

**Comment by amanbha** [comment]
Yes, it stores some metadata about the actors which were created. To completely remove everything for the Actor, you should use Delete the actor https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-lifecycle#deleting-actors-and-their-state

**Comment by woszszo** [comment]
That's a bit unfortunate. It means that if I keep creating volatile actors and don't delete them explicitly I'll run out of RAM eventually.

I'm wondering if I could register some periodic callback which cleans old actors automatically without creating separate service...

**Comment by amanbha** [comment]
@woszszo yes, currently for deletion you will have to call explicitly from outside of actor to delete the actors. 
One approach without an external service, is that you can write your ActorService deriving from ActorService and override the RunAsync method. In RunAsync, you can periodically query for Actors in that partition and based on some flag in Actor's state, you can make DeleteActor calls.

**Comment by woszszo** [comment]
Thanks! I'll try this approach.

**Comment by amanbha** [comment]
@woszszo I am closing this issue, please feel free to reopen if you still have questions.

**Comment by goenning** [comment]
@amanbha hey, this thread is very informative, thanks for the discussion.

Does the same apply to an Actor in which StatePersistence is None? Do we still need to remove actors which does not have StatePersistence? I suppose the metadata is still persisted somewhere, right?

**Comment by amanbha** [comment]
@goenning When state persistence is None, the state is not replicated and persisted to other replicas. So when the primary replica failsover all the state is gone. You don't need to remove actors or state, periodically you can just failover the actor service process and all state will be gone.
