### ISSUE TITLE
Rename field Singleton to Instance

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-services-and-actors-dotnet#89]
I find out that some classes has field named `Singleton`
like in type `ServiceCodeBuilder`

`static ICodeBuilder Singleton = new ServiceCodeBuilder();`

but actually this type is not implement Singleton pattern. So, it may be a little confusing. Maybe it would better to rename it to `Instance` ?

Here are a list of classes that has field named `Singleton`:
   -  [ServicePartitionKey](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/077fa5fda532ac3ba0ff5215777986581b878e83/src/Microsoft.ServiceFabric.Services/Client/ServicePartitionKey.cs#L21)
   - [ServiceCodeBuilder](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/077fa5fda532ac3ba0ff5215777986581b878e83/src/Microsoft.ServiceFabric.Services.Remoting/V1/Builder/ServiceCodeBuilder.cs#L16) 
   - [ActorCodeBuilder](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/077fa5fda532ac3ba0ff5215777986581b878e83/src/Microsoft.ServiceFabric.Actors/Remoting/V2/Builder/ActorCodeBuilder.cs#L21)
   - [ActorEventSubscriberManager](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/077fa5fda532ac3ba0ff5215777986581b878e83/src/Microsoft.ServiceFabric.Actors/Remoting/V1/Client/ActorEventSubscriberManager.cs#L19)
   - [ActorDataContractSurrogate](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/077fa5fda532ac3ba0ff5215777986581b878e83/src/Microsoft.ServiceFabric.Actors/Remoting/ActorDataContractSurrogate.cs#L17)

In some cases it's look likes a breaking changes. What do you think about it?

**Comment by amanbha** [comment]
@Marusyk Sure, makes sense, can be renamed except the public one(which would be breaking)

**Comment by Marusyk** [comment]
@amanbha thanks for quick response.  

One more suggestion. We have that static properties that creates a new instance. It is not quite as lazy.

The laziness of type initializers is only guaranteed by .NET when the type isn't marked with a special flag called beforefieldinit. Unfortunately, the C# compiler marks all types which don't have a static constructor as beforefieldinit. Note that it affects performance. See [this article with more details about this issue](http://csharpindepth.com/Articles/General/BeforeFieldInit.aspx).

Is it make sense to add explicit static constructor to tell C# compiler not to mark type as beforefieldinit and improve performance?

**Comment by amanbha** [comment]
@Marusyk we were not looking at lazy initialization for all of them specially, if they are in hot path of request response processing.
