### ISSUE TITLE
Does SF guarantee that exactly single thread executed the actor code at particular moment.

### ISSUE THREAD

**Issue by woszszo** [Azure/service-fabric-services-and-actors-dotnet#90]
Does SF guarantee that *exactly* single thread on *single* machine (node) can have the actor lock acquired in *any* circumstances? Should I expect this during the replica switch?

Should I consider it a bug if the guarantee is broken?

**Comment by amanbha** [comment]
During Replica change roles, call can be sent to new primary, while the call in older primary replica continues to execute, however the method executing in older primary will not be able to change state of the actor. Actor method calls should be idempotent to handle this.

**Comment by woszszo** [comment]
What is the best advice to detect it? We are using actor to guarantee exclusive access to some resources and this particular case breaks this guarantee.

**Comment by amanbha** [comment]
@woszszo  Let me explain it a bit more:
In addition to ChangeRole, there can still be scenarios(eg. node running primary loosing connectivity with other nodes and hence ChangeRole on it cannot be called.) where an existing replica keeps on running operations but its write access will be revoked so any state changes will not be allowed. The guarantee from the platform is that there will be one primary replica at any given time and in that primary replica only one method call will be allowed for an actor id. Older primary replicas can have code executing a method for calls made to them but they will not have write access and any attempt to save state will throw exception.
One option is to SaveState in the method before giving access. What resource is this, if its remote resource then remote resource should control the access and the access should not be controlled by actors. Adding @harahma for more inputs.

**Comment by woszszo** [comment]
@amanbha 
Thanks for exhausting explanation. This helps a lot to understand the issue.

> One option is to SaveState in the method before giving access. What resource is this, if its remote resource then remote resource should control the access and the access should not be controlled by actors. 

I see, basically we need to change the approach.
