### ISSUE TITLE
VS Actor Template Does Not Compile

### ISSUE THREAD

**Issue by vturecek** [Azure/service-fabric-services-and-actors-dotnet#91]
The Interface project from an actor VS 2017 template does not compile with an error on line 10 stating RemotingListener could not be found. The line is: [assembly: FabricTransportActorRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)]

**Comment by mjanulaitis** [comment]
This failed only before I updated to the latest RemotingListener version.

**Comment by vturecek** [comment]
@mjanulaitis were you able to update everything to the latest version to get that sorted out?

**Comment by mjanulaitis** [comment]
Sir yes sir.  Thank you.

Mike Janulaitis
801-910-4256
mike@uppersetting.com

________________________________
