### ISSUE TITLE
Question: Long Deployment Times and Actors In Warning States

### ISSUE THREAD

**Issue by keggster101020** [Azure/service-fabric-services-and-actors-dotnet#96]
I have an Azure Service Fabric Reliable Actors service with 50+ different actor types. When I try and deploy using CI to my cluster using VSTS "Deploy service fabric application" task it takes about 2 hours on average to complete. This seems rather high and I'm not able to correlate what causes the high upgrade time.

Also, shortly after deployments, some of my actors are in warning state with the warning at the following levels:

- Partition
   >Partition reconfiguration is taking longer than expected
- Replica
    >The api IStatefulServiceReplica.ChangeRole(P) on node _Node01_2 is stuck

I would like to know: 

 1. Why do deployments take so long and what are some contributing factors that can lead to an increased roll-out time for actor services? (IE: large states?)
 2. Some of my actors are tagged for state persistence but aren't utilizing state manager currently, can this cause deployment issues when trying to migrate state during upgrade? 
 3. What are the warnings for the actors related too and how can I debug these errors?

Thanks!

**Comment by amanbha** [comment]
This doc explains how the upgrades are done: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade 
During the upgrade services in one UD are brought down and are moved to other UDs so your nodes in other UDs must handle the replica loads.
How many nodes and what machine types are in the cluster? What is the target and min replica set size of the actor services?

**Comment by keggster101020** [comment]
5 Node Cluster with Windows Server 2016 Datacenter as the hosting OS. 

Per Application manifest, all actors have
- MinReplicaSetSize = 3
- PartitionCount = 3
- TargetReplicaSetSize = 3

Are actor services brought down regardless of the actor queue and current processes by using the default cancellation token passed to actors?

**Comment by amanbha** [comment]
Have you overridden the partition and replica sizes during the deployment. 
What is the actual number running in the cluster, you can check it in Service fabric Explorer. What type of machines are these, how much cpu cores and RAM?
Going by the numbers you provides, you have 50+ services, that's a minimum of 50*3*3 = 450 replicas. Roughly around 100 replicas per machine, which is too high given that during the upgrade they need to be moved to nodes in other upgrade domains. You need to have more machines in the cluster to handle this.

**Comment by keggster101020** [comment]
The partition and replica's are being changed in the application manifest before deployment (manual code changes). 

Per the service fabric explorer at the cluster level: we have 99 services with 263 partitions and 719 replicas. 

Machines are VM Scale Sets in Azure: 14GB Ram, 200GB SSD, 4VCPUs,

**Comment by amanbha** [comment]
That replica density is too high for the machines and can cause issues during upgrades, when 1 UD will be down and replicas will be moved to other nodes. You need to add more machines to your cluster. Try to keep ~80 for each node with performance testing that the nodes will be able handle the loads.

**Comment by keggster101020** [comment]
Ok, in the meantime I'll drop the replica count on some of my actors.

Thanks!

**Comment by veatcha** [comment]
@amanbha Can you provide any insight into the comment about a replica density of ~80 per node?   

I wasn't sure if that was specific to the VM SKU listed above, or if that's a general best practice.  

We have experienced these same errors recently, not at all during normal operation, just during upgrades.  And while our nodes are never burdened from a CPU/RAM perspective (they are doing very lightweight operations), I assume there must be some network/disk overhead associated with state being persisted on secondaries, made worse by the movement of replicas.

We are currently running ~500 replicas over a 5 node cluster that is less powerful than the one mentioned above (D2_v3:  2 VPUs, 8GB Ram, 50GB SSD) , so I assume your same guidance stands, but I'm wondering if there's any way for us to gain visibility into how to make those decisions?

Thank you!
Andrew
